# ===================================================
# meta infos
# ===================================================

meta:
  project: yocto-images
  include:
    - version.yaml
    - dobi.yaml
    - cpu01-base-image/dobi.yaml
    - cpu01-devtools-image/dobi.yaml
    - cpu01-edgefarm-image/dobi.yaml
    - cpu01-edgefarm-devtools-image/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version
