# ===================================================
# meta infos
# ===================================================

meta:
  project: ci.os.lmp
  include:
    - version.yaml
    - dobi.yaml
    - yocto/.generated_dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version


