# ===================================================
# meta infos
# ===================================================

meta:
  project: yocto-images
  include:
    - version.yaml
    - dobi.yaml
    - base-image/dobi.yaml
    - edgefarm-image/dobi.yaml
    - devtools-image/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
    - buildingblock-version
