BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "oss-compliance"
BBFILE_PATTERN_oss-compliance = "^${LAYERDIR}/"
BBFILE_PRIORITY_oss-compliance = "99"
LAYERDEPENDS_oss-compliance = "core"
LAYERSERIES_COMPAT_oss-compliance = "scarthgap"
