name: Build Ci4Rail Base Image
on:
  pull_request:
    branches:
      - main
    paths:
      - "base"
      - "kas-includes"
      - "scripts"
      - ".github/workflows/base-pull-request.yaml"

jobs:
  build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sleep 20 && echo Hello, world!

      # Runs docker hello-world
      - name: Hello from Docker
        run: docker run hello-world
