name: CPU01 Base Image
on:
  pull_request:
    branches:
      - main
    paths:
      - "cpu01-base-image/kasfile.yaml"
      - "kas-includes/kasfile-tdxbsp.yaml"
      - "kas-includes/kasfile-docker.yaml"
      - "kas-includes/kasfile-general.yaml"
      - ".github/workflows/cpu01-base-image.yaml"
  push:
    branches:
      - main
    paths:
      - "cpu01-base-image/kasfile.yaml"
      - "kas-includes/kasfile-tdxbsp.yaml"
      - "kas-includes/kasfile-docker.yaml"
      - "kas-includes/kasfile-general.yaml"
      - ".github/workflows/cpu01-base-image.yaml"

env:
  IMAGE_TYPE: base
  MACHINE: cpu01
  BUILDER_IMAGE: ghcr.io/siemens/kas/kas:2.6.3
  MACHINE_DIR: moducop-cpu01
  IMAGE_START: Moducop-CPU01_Base-Image
  TARFILE_ENDING: ci4rail_tezi
  ROBOT_IMAGE: ci4rail/robot:latest-2021-03-25
  TEST_COMPUTER_IP: 192.168.24.12
  DOCKER_USERNAME: ci4rail
  ARTEFACT_IMAGE_NAME: cpu01-base-image

jobs:
  calculate-version:
    name: Calculate Version
    # Currently not working with Ubuntu 20.04
    runs-on: ubuntu-18.04
    outputs:
      #0.1.0-36.cleanup.e3132eb42a917c62b1f9198def62e78a4346c35d
      version: ${{ steps.gitversion.outputs.majorMinorPatch }}-${{ steps.gitversion.outputs.commitsSinceVersionSource }}.${{ github.event.pull_request.head.ref }}.${{ steps.shortSha.outputs.shortSha }}
      name_suffix: ${{ steps.eventCheck.outputs.nameSuffix }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Get git sha as on PR gitversion provides incorrect sha
        id: shortSha
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=shortSha::`echo ${{ github.event.pull_request.head.sha }} | cut -c1-8`"
          elif [ "$EVENT_NAME" = "push" ]; then
              echo "::set-output name=shortSha::${GITHUB_SHA::8}"
          else
              echo "::set-output name=shortSha::invalid"
          fi
      - name: Generate Image name dependend on github event
        id: eventCheck
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
              echo "::set-output name=nameSuffix::-pr"
          elif [ "$EVENT_NAME" = "push" ]; then
              echo "::set-output name=nameSuffix::"
          else
              echo "::set-output name=nameSuffix::-invalid"
          fi

  build-and-push-image:
    needs: calculate-version
    name: Build and Push Image
    runs-on: [self-hosted, linux, x64, yocto-runner]
    outputs:
      bucket: ${{ env.MACHINE }}-${{ env.IMAGE_TYPE }}${{ needs.calculate-version.outputs.name_suffix }}
      nameSuffix: ${{ needs.calculate-version.outputs.name_suffix }}
      version: ${{ needs.calculate-version.outputs.version }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Cache for Yocto Builds
        if: github.event_name == 'pull_request'
        run: |
          rsync -rht --ignore-missing-args /yocto-cache/downloads/* /downloads/
          rsync -rht --ignore-missing-args /yocto-cache/sstate-cache/* /sstate-cache/

      - name: Log into Docker
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo ${DOCKER_PASSWORD} | docker login ${DOCKER_REGISTRY} -u ${DOCKER_USERNAME} --password-stdin

      - name: Build Yocto
        env:
          # Required internally for build
          IMAGE_NAME_SUFFIX: ${{ needs.calculate-version.outputs.name_suffix }}
          IMAGE_GIT_VERSION: ${{ needs.calculate-version.outputs.version }}
        run: |
          docker run \
                -v /install:/install \
                -v /sstate-cache:/sstate-cache \
                -v /downloads:/downloads \
                -v ${GITHUB_WORKSPACE}/${MACHINE}-${IMAGE_TYPE}-image:/work \
                -v ${GITHUB_WORKSPACE}/kas-includes:/kas-includes \
                -e USER_ID=$(id -u ${USER}) \
                -e GROUP_ID=$(id -g ${USER}) \
                -e IMAGE_NAME_SUFFIX=${IMAGE_NAME_SUFFIX} \
                -e IMAGE_GIT_VERSION=${IMAGE_GIT_VERSION} \
                -w /work \
                ${BUILDER_IMAGE} \
                build kasfile.yaml

      - name: Store Cache for Yocto Builds
        if: github.event_name == 'pull_request'
        run: |
          rsync -rht /downloads/* /yocto-cache/downloads/
          rsync -rht /sstate-cache/* /yocto-cache/sstate-cache/

      - name: Check Build Artefacts are there
        id: artefacts
        env:
          TAR_IMAGE_PATH: /install/images/${{ env.MACHINE_DIR }}/${{ env.IMAGE_START }}_${{ needs.calculate-version.outputs.version }}${{ needs.calculate-version.outputs.name_suffix }}-${{ env.TARFILE_ENDING }}.tar
        run: |
          ls -t ${TAR_IMAGE_PATH}
          mkdir ${GITHUB_WORKSPACE}/minio
          cp ${TAR_IMAGE_PATH} ${GITHUB_WORKSPACE}/minio

      - name: Push Images to Minio
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: https://minio.ci4rail.com
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: ${{ env.MACHINE }}-${{ env.IMAGE_TYPE }}${{ needs.calculate-version.outputs.name_suffix }}
          source_dir: minio
          target_dir: "/"

  test-image:
    needs: [calculate-version, build-and-push-image]
    name: Test Yocto Image
    runs-on: ubuntu-latest
    steps:
      - uses: ci4rail/teststation-action@v1
        with:
          pipeline-name: "${{ github.repository }}"
          # This name is resolved by tailscale magic DNS
          mqtt-broker-url: "lizard-rpi:1883"
          test-name: "moducop base-image test"
          artifact-override: |
            {
              \"desired_versions.cpu_firmware.version\": \"${{ env.ARTEFACT_IMAGE_NAME }}-${{ needs.calculate-version.outputs.version }}${{ needs.calculate-version.outputs.name_suffix }}\",
              \"desired_versions.cpu_firmware.method\": \"toradex-installer\",
              \"desired_versions.cpu_firmware.source.type\": \"ci4rail-minio\",
              \"desired_versions.cpu_firmware.source.bucket\": \"${{ needs.build-and-push-image.outputs.bucket }}\",
              \"desired_versions.cpu_firmware.source.file\": \"${{ env.IMAGE_START }}_${{ needs.calculate-version.outputs.version }}${{ needs.calculate-version.outputs.name_suffix }}-${{ env.TARFILE_ENDING }}.tar\"
            }
          access-token: ${{ secrets.FW_CI_TOKEN }}
          tailscale-key: ${{ secrets.YODA_TAILSCALE_AUTHKEY }}
