name: CPU01Plus Edgefarm Image
on:
  pull_request:
    branches:
      - main
    paths:
      - "cpu01plus-edgefarm-image/kasfile.yaml"
      - "kas-includes/kasfile-tdxbsp.yaml"
      - "kas-includes/kasfile-docker.yaml"
      - "kas-includes/kasfile-mender.yaml"
      - "kas-includes/kasfile-mender-tdxbsp.yaml"
      - "kas-includes/kasfile-general.yaml"
      - "kas-includes/kasfile-edgefarm.yaml"
      - ".github/workflows/cpu01plus-edgefarm-image.yaml"
      - ".github/workflows/image-workflow.yaml"
  push:
    branches:
      - main
    paths:
      - "cpu01plus-edgefarm-image/kasfile.yaml"
      - "kas-includes/kasfile-tdxbsp.yaml"
      - "kas-includes/kasfile-docker.yaml"
      - "kas-includes/kasfile-mender.yaml"
      - "kas-includes/kasfile-mender-tdxbsp.yaml"
      - "kas-includes/kasfile-general.yaml"
      - "kas-includes/kasfile-edgefarm.yaml"
      - ".github/workflows/cpu01plus-edgefarm-image.yaml"
      - ".github/workflows/image-workflow.yaml"

jobs:
  workflow-call:
    uses: ./.github/workflows/image-workflow.yaml
    with: 
      machine: "cpu01plus"
      machine_dir: "moducop-cpu01plus"
      image_type: "edgefarm"
      output_type: "tar"
      image_start: "Moducop-CPU01Plus_Edgefarm-Image"
      test_name: ""
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      mender_tenant_token: ${{ secrets.MENDER_TENANT_TOKEN }}
      minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
      minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
      mender_user_email: ${{ secrets.MENDER_USER_EMAIL }}
      mender_password: ${{ secrets.MENDER_PASSWORD }}
      private_token: ${{ secrets.FW_CI_TOKEN }}
      tailscale_auth_key: ${{ secrets.YODA_TAILSCALE_AUTHKEY }}