name: Raspberry Pi 4 EdgeFarm Devtools Image
on:
  pull_request:
    branches:
      - main
    paths:
      - "raspberrypi4-64-edgefarm-devtools-image/kasfile.yaml"
      - "kas-includes/kasfile-raspberrypi.yaml"
      - "kas-includes/kasfile-docker.yaml"
      - "kas-includes/kasfile-mender.yaml"
      - "kas-includes/kasfile-general.yaml"
      - "kas-includes/kasfile-edgefarm-devtools.yaml"
      - ".github/workflows/raspberrypi4-64-edgefarm-devtools-image.yaml"
      - ".github/workflows/image-workflow.yaml"
  push:
    branches:
      - main
    paths:
      - "raspberrypi4-64-edgefarm-devtools-image/kasfile.yaml"
      - "kas-includes/kasfile-raspberrypi.yaml"
      - "kas-includes/kasfile-docker.yaml"
      - "kas-includes/kasfile-mender.yaml"
      - "kas-includes/kasfile-general.yaml"
      - "kas-includes/kasfile-edgefarm-devtools.yaml"
      - ".github/workflows/raspberrypi4-64-edgefarm-devtools-image.yaml"
      - ".github/workflows/image-workflow.yaml"

jobs:
  workflow-call:
    uses: ./.github/workflows/image-workflow.yaml
    with: 
      machine: "raspberrypi4-64"
      machine_dir: "raspberrypi4-64"
      image_type: "edgefarm-devtools"
      output_type: "sdimg"
      image_start: "raspberrypi4-64_EdgeFarm-Devtools-Image"
      test_name: ""
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      mender_tenant_token: ${{ secrets.MENDER_TENANT_TOKEN }}
      minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
      minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
      mender_user_email: ${{ secrets.MENDER_USER_EMAIL }}
      mender_password: ${{ secrets.MENDER_PASSWORD }}
      private_token: ${{ secrets.FW_CI_TOKEN }}
      tailscale_auth_key: ${{ secrets.YODA_TAILSCALE_AUTHKEY }}