name: "test testing"

on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test Name'
        required: false
        default: 'cpu01-standard-image test'
      test_station:
        description: 'Test Station'
        required: true
        default: 'lizard-rpi:1883'
      som_type:
        description: 'SoM Type'
        required: true
        default: 'verdin-imx8mm'

env:
  TESTSTATION_MQTT_URL: ${{ inputs.test_station }}

jobs:
  calculate-version:
    runs-on: ubuntu-22.04
    outputs:
      version: "2.3.0"
      name_suffix: ""
      mender_tezi_file_name: Moducop-CPU01_Standard-Image_2.3.0.mender_tezi.tar
    steps:
      - name: fake
        run: |
          echo "calculating version"

  build-and-push-image:
    runs-on: ubuntu-22.04
    outputs:
      bucket: cpu01-standard
    steps:
      - name: fake
        run: |
          echo "building and pushing image"

  test-image:
    if: inputs.test_name != ''
    needs: [calculate-version, build-and-push-image]
    name: Test Yocto Image
    runs-on: ubuntu-22.04
    steps:
      - uses: ci4rail/teststation-action@update_test_scheduler
        with:
          pipeline-name: "${{ github.run_id }}"
          mqtt-broker-url: ${{ env.TESTSTATION_MQTT_URL }}
          test-name: ${{ inputs.test_name }}
          artifact-override: |
            {
              \"desired_versions.cpu_firmware.version.version_string\": \"${{ inputs.image_start }}_${{ needs.calculate-version.outputs.version }}${{ needs.calculate-version.outputs.name_suffix }}\",
              \"desired_versions.cpu_firmware.method\": \"toradex-installer\",
              \"desired_versions.cpu_firmware.cputype\": \"${{ inputs.som_type }}\",
              \"desired_versions.cpu_firmware.source.type\": \"ci4rail-minio\",
              \"desired_versions.cpu_firmware.source.bucket\": \"${{ needs.build-and-push-image.outputs.bucket }}\",
              \"desired_versions.cpu_firmware.source.file\": \"${{ needs.calculate-version.mender_tezi_file_name }}\"
              \"desired_versions.cpu_firmware.force_update\": "true\",
            }
          access-token: ${{ secrets.private_token }}
          tailscale-key: ${{ secrets.tailscale_auth_key}}
          request-timeout: "7200"
