name: Test workflow
on:
  pull_request:
    branches:
      - main
jobs:
  workflow-call:
    uses: ./.github/workflows/image-workflow.yaml
    with: 
      machine: "cpu01"
      image_type: "edgefarm-devtools"
      docker_username: "ci4rail"
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
