name: "test testing"

on:
  push:
    branches:
      - scarthgap-test-ci

env:
  TESTSTATION_MQTT_URL: lizard-rpi:1883

jobs:
  calculate-version:
    runs-on: ubuntu-22.04
    outputs:
      version: "2.3.0"
      name_suffix: ""
      mender_tezi_file_name: "Moducop-CPU01_Standard-Image_2.3.0.mender_tezi.tar"
    steps:
      - name: fake
        run: |
          echo "calculating version"

  build-and-push-image:
    runs-on: ubuntu-22.04
    outputs:
      bucket: cpu01-standard
    steps:
      - name: fake
        run: |
          echo "building and pushing image"
  #
  test-image:
    needs: [calculate-version, build-and-push-image]
    name: Test Yocto Image
    runs-on: ubuntu-22.04
    steps:
      - uses: ci4rail/teststation-action@update_test_scheduler
        with:
          pipeline-name: "${{ github.run_id }}"
          mqtt-broker-url: ${{ env.TESTSTATION_MQTT_URL }}
          test-name: cpu01-standard-image test
          artifact-override: |
            {
              \"desired_versions.cpu_firmware.version.version_string\": \"Moducop-CPU01_Standard-Image_${{ needs.calculate-version.outputs.version }}${{ needs.calculate-version.outputs.name_suffix }}\",
              \"desired_versions.cpu_firmware.method\": \"toradex-installer\",
              \"desired_versions.cpu_firmware.cputype\": \"verdin-imx8mm\",
              \"desired_versions.cpu_firmware.source.type\": \"ci4rail-minio\",
              \"desired_versions.cpu_firmware.source.bucket\": \"${{ needs.build-and-push-image.outputs.bucket }}\",
              \"desired_versions.cpu_firmware.source.file\": \"${{ needs.calculate-version.outputs.mender_tezi_file_name }}\",
              \"desired_versions.cpu_firmware.force_update\": \"false\"
            }
          access-token: ${{ secrets.FW_CI_TOKEN }}
          tailscale-key: ${{ secrets.YODA_TAILSCALE_AUTHKEY }}
          request-timeout: "7200"
          minio_access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          minio_secret_key: ${{ secrets.MINIO_SECRET_KEY }}
